# Generated by Django 5.2.1 on 2025-06-15 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'Productgallery', 'verbose_name_plural': 'product gallery'},
        ),
    ]
